/**
 * Converts a single domain name label to its ASCII representation using the
 * runtime's built-in UTS#46 (Unicode IDNA Compatibility Processing) via the
 * URL constructor.
 *
 * This satisfies RFC 6265 Section 6.3's IDNA guidance: "User agents SHOULD
 * implement IDNA2008 [RFC5890] and MAY implement [UTS46]". The URL constructor
 * in all major JS runtimes (Node.js, Deno, Bun, browsers) implements UTS#46
 * via ICU, which includes the full IDNA pipeline: Unicode mapping, NFC
 * normalization, validation, and punycode encoding.
 *
 * We use the URL constructor rather than a dedicated dependency like `tr46` or
 * `punycode` because:
 * - `tr46` would add ~210KB (mostly a Unicode mapping table already in the runtime)
 * - `punycode` only handles the encoding step, missing IDNA mapping/normalization
 * - The URL constructor provides the complete UTS#46 pipeline at zero size cost
 *
 * Labels are routed based on their type:
 * - `xn--` prefix (potential A-label): validated via URL constructor
 * - Non-ASCII (U-label): converted via URL constructor
 * - ASCII without `xn--` (NR-LDH or other): lowercased directly
 *
 * @returns The ASCII label, or null if conversion failed
 */
function labelToASCII(label: string): string | null {
  // Empty labels (from trailing dots or consecutive dots) pass through unchanged
  if (label === '') {
    return ''
  }

  const lower = label.toLowerCase()

  // Labels starting with xn-- may be A-labels (valid punycode) or Fake A-labels
  // (invalid punycode). Route through URL constructor to validate.
  if (lower.startsWith('xn--')) {
    try {
      new URL(`http://${lower}.example`)
      return lower
    } catch {
      // Fake A-label — URL constructor rejects invalid punycode.
      // Currently returns the label as-is to preserve backward compatibility.
      // draft-ietf-httpbis-rfc6265bis-22 Step 4 would reject this (return null).
      return lower
    }
  }

  // Non-ASCII labels (U-labels) need IDNA conversion to A-labels
  if (/[^\u0001-\u007f]/.test(label)) {
    try {
      const hostname = new URL(`http://${label}.example`).hostname
      // Extract the converted label (everything before ".example")
      const dotIndex = hostname.lastIndexOf('.example')
      return dotIndex > 0 ? hostname.slice(0, dotIndex) : hostname
    } catch {
      // Conversion failed — currently returns null.
      // The caller preserves backward compatibility by falling back.
      return null
    }
  }

  // ASCII-only, no xn-- prefix: NR-LDH label (or non-standard like underscores).
  // Step 2 is a no-op for NR-LDH labels — just lowercase.
  return lower
}

/**
 * Implements the "Canonicalized Host Names" algorithm from
 * {@link https://www.rfc-editor.org/rfc/rfc6265.html#section-5.1.2 | RFC 6265 Section 5.1.2}.
 *
 * This function contains ONLY the RFC-specified steps. Library-specific
 * concerns (whitespace trimming, leading-dot stripping, IPv6 handling)
 * are handled by the caller ({@link canonicalDomain}).
 *
 * @remarks
 * ### RFC 6265 - 5.1.2. Canonicalized Host Names
 *
 * A canonicalized host name is the string generated by the following
 * algorithm:
 *
 * 1.  Convert the host name to a sequence of individual domain name
 *     labels.
 *
 * 2.  Convert each label that is not a Non-Reserved LDH (NR-LDH) label,
 *     to an A-label (see Section 2.3.2.1 of [RFC5890] for the former
 *     and latter), or to a "punycode label" (a label resulting from the
 *     "ToASCII" conversion in Section 4 of [RFC3490]), as appropriate
 *     (see Section 6.3 of this specification).
 *
 * 3.  Concatenate the resulting labels, separated by a %x2E (".")
 *     character.
 *
 * ### IDNA Implementation (Section 6.3)
 *
 * RFC 6265 Section 6.3 states: "User agents SHOULD implement IDNA2008
 * [RFC5890] and MAY implement [UTS46] or [RFC5895]". This implementation
 * uses the runtime's URL constructor which provides UTS#46 processing
 * via ICU. See the {@link labelToASCII} helper for details.
 *
 * ### Compatibility with draft-ietf-httpbis-rfc6265bis-22
 *
 * The latest draft expands this algorithm to 5 steps, adding validation
 * that rejects invalid label types (Step 2) and Fake A-labels (Step 4).
 * These changes were introduced in response to a DNS Directorate review
 * ({@link https://lists.w3.org/Archives/Public/ietf-http-wg/2025JanMar/0140.html})
 * which identified that the original algorithm was underspecified for a
 * function whose output is used in security decisions. The draft also
 * removes Section 6.3 (IDNA transition guidance), scoping the spec to
 * ASCII-only name resolution systems. This stricter validation is not
 * yet implemented but the label-by-label structure supports adding it.
 *
 * @param hostName - a domain name (NOT an IPv6 address) to canonicalize
 * @returns the canonicalized host name
 */
export function canonicalizedHostName(hostName: string): string {
  // Step 1: "Convert the host name to a sequence of individual domain name
  //          labels."
  const labels = hostName.split('.')

  // Step 2: "Convert each label that is not a Non-Reserved LDH (NR-LDH) label,
  //          to an A-label (see Section 2.3.2.1 of [RFC5890] for the former and
  //          latter), or to a "punycode label" (a label resulting from the
  //          "ToASCII" conversion in Section 4 of [RFC3490]), as appropriate
  //          (see Section 6.3 of this specification)."
  const converted = labels.map((label) => labelToASCII(label) ?? label)

  // Step 3: "Concatenate the resulting labels, separated by a %x2E (".")
  //          character."
  return converted.join('.')
}
